// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_layout from "./routes/_layout.tsx";
import * as $favoritos from "./routes/favoritos.tsx";
import * as $index from "./routes/index.tsx";
import * as $personajes from "./routes/personajes.tsx";
import * as $weather from "./routes/weather.tsx";
import * as $AgregarAFavoritos from "./islands/AgregarAFavoritos.tsx";
import * as $ClimaPanel from "./islands/ClimaPanel.tsx";
import * as $FavoritoButton from "./islands/FavoritoButton.tsx";
import * as $GaleriaPersonaje from "./islands/GaleriaPersonaje.tsx";
import * as $Header from "./islands/Header.tsx";
import * as $ListaFavoritos from "./islands/ListaFavoritos.tsx";
import * as $ModalTrailer from "./islands/ModalTrailer.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_layout.tsx": $_layout,
    "./routes/favoritos.tsx": $favoritos,
    "./routes/index.tsx": $index,
    "./routes/personajes.tsx": $personajes,
    "./routes/weather.tsx": $weather,
  },
  islands: {
    "./islands/AgregarAFavoritos.tsx": $AgregarAFavoritos,
    "./islands/ClimaPanel.tsx": $ClimaPanel,
    "./islands/FavoritoButton.tsx": $FavoritoButton,
    "./islands/GaleriaPersonaje.tsx": $GaleriaPersonaje,
    "./islands/Header.tsx": $Header,
    "./islands/ListaFavoritos.tsx": $ListaFavoritos,
    "./islands/ModalTrailer.tsx": $ModalTrailer,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
